language: scala

env:
  - CROMWELL_VERSION=31

script:
  - wget https://github.com/broadinstitute/cromwell/releases/download/$CROMWELL_VERSION/womtool-$CROMWELL_VERSION.jar
  - for file in $(find -name "*.wdl"); do echo "validating $file"; java -jar womtool-$CROMWELL_VERSION.jar validate $file; done
  - wget https://github.com/broadinstitute/cromwell/releases/download/$CROMWELL_VERSION/cromwell-$CROMWELL_VERSION.jar
  - sbt -Dbiowdl.output_dir=test-output -Dcromwell.jar=cromwell-$CROMWELL_VERSION.jar clean evicted scalafmt headerCheck test